### ISSUE TITLE
Robolectric tests started to fail since Android Build Tools 28.0.3 was added

### ISSUE THREAD

**Issue by juanimoli** [circleci/circleci-images#273] opened 2018-11-01 19:05 UTC
Hi!

We're experiencing issues with the latests images of Android in CircleCI. We're using api-27-alpha image for our builds, and since [this change](https://github.com/circleci/circleci-images/pull/268) some tests with Robolectric started to fail. 

There were no changes made in the Robolectric version that we use, neither in our internal dependencies. Also, if we run the same command that we excecute in CI, it works in either Android Studio, and in Terminal. All repositories we've seen this issue are running Gradle 3 with Android Build Tools 27.0.2. We're seeing the following stacktrace in all failed tests:

```
test > testWithRobolectric FAILED
    java.lang.AssertionError: java.lang.IllegalAccessException: no such field: org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/699139716.__proxy__/android.content.res.Configuration/putField

        Caused by:
        java.lang.IllegalAccessException: no such field: org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/699139716.__proxy__/android.content.res.Configuration/putField

            Caused by:
            java.lang.LinkageError: loader constraint violation: when resolving field "__proxy__" the class loader (instance of <bootloader>) of the referring class, org/robolectric/internal/bytecode/ProxyMaker$GeneratedProxy, and the class loader (instance of org/robolectric/internal/bytecode/SandboxClassLoader) for the field's resolved type, android/content/res/Configuration, have different Class objects for that type

test > anotherRobolectricTest FAILED
    java.lang.NoClassDefFoundError: Could not initialize class android.content.res.Configuration

test > yetAnotherRobolectricTest FAILED
    java.lang.NoClassDefFoundError: Could not initialize class android.content.res.Configuration

```

I've already made a ticket in the support website, in which we were suggested to change the image to the latests success build's image, which actually works. We want to have as image **api-27-alpha** rather than the fixed hash, because of future changes.

Is there anything we have to change from our side?

Thanks,

Juan.

**Comment by barbosa** [comment] 2018-11-20 22:01
Would you mind sharing the image you have used to make it work, @juanimoli ?

**Comment by juanimoli** [comment] 2018-11-22 14:18
@barbosa we've been using the latest that worked in the same repository we're putting it. So for every repository, it might change. But here is an example:

> circleci/android@sha256:8c2815a3da3f1ba2e959157132cac28e00e7b8bf6c32d447eace67c184d4fa0e

**Comment by pedrohperalta** [comment] 2018-11-22 16:51
Thanks @juanimoli and @barbosa, I was able to make the project work here again by pointing to the latest image in which the builds worked.

**Comment by technoir42** [comment] 2018-11-24 13:00
I'm not sure how installing Build Tools 28.0.3 by default is related to those errors.
Each version of Android Gradle Plugin has a hard-coded version of Build Tools it'll use (unless you override `buildToolsVersion`), if that version is not installed then AGP will download it before build. AGP 3.3.0-3.4.0 need 28.0.3, so pre-installing it reduced build time.

FWIW my Robolectric tests run just fine with AGP 3.3.0-beta04, Gradle 4.10.2 and Robolectric 4.0.2.

**Comment by juanimoli** [comment] 2018-11-26 19:07
@technoir42 we're using JUnit 4.12 and Robolectric 3.3.+ with Android Build Tools 27.0.2
Android Gradle Plugin 2.3.3 and Gradle 3.5.1. There were no changes made in those versions neither in the tests that begin to fail. By quick searching through changes in the images, I found that change in the Build Tools but I don't really know if thats the real cause. The thing is, downgrading to an older image, it works. So maybe it's a change we have to make in our configuration.

@pedrohperalta were you experiencing the same issue? Can you share what versions are you using please? So we can compare and maybe find a lead.

**Comment by pedrohperalta** [comment] 2018-11-26 19:21
@juanimoli Yes, I was having the same issue. I'm using Android Build Tools 27.1.1, JUnit 4.12 and Robolectric 3.6.1.

**Comment by GMuniz** [comment] 2018-12-04 13:31
We are having exactly the same issue, with same stack as @juanimoli quoted.

Not all the previous hashes worked for me, but found one image did.

Do we have an ETA when this is going to be solved?

**Comment by guillaume-tgl** [comment] 2018-12-14 15:46
I've had the same issue since beginning of November using image `circleci/android:api-28-ndk-r17b` and I had to specify an old image SHA to make my tests pass (`e25d35d689aa52eba6af058e1da6b2247789c9f21cbf73b70fee6fafe6ebfd85` in my case).

**Comment by joshfriend** [comment] 2019-06-18 14:29
The build tools version is [usually automatic](https://developer.android.com/studio/releases/build-tools), if it switches to a newer version that breaks your build, you should pin the build-tools version (instead of the docker image):

```groovy
android {
    buildToolsVersion "28.0.2"
}
```

I don't think any of the issues here are caused by the docker image.

**Comment by juanimoli** [comment] 2019-06-18 14:59
@joshfriend the image that we were using was deprecated. In order to receive new updates on Android images, we needed to move to the non-alpha image, which was throwing that message even if we had the buildTools pinned (we always use it pinned). We managed to fix it by upgrading Robolectir as @tetsukay said earlier. There is no retrocompatibility :(

**Comment by eddiewebb** [comment] 2019-11-09 00:30
> I solved this problem by doing Robolectric version update from 3.6.1 to 3.8.

Thank you @tetsukay.  Closing this issue.

**Closed by eddiewebb** 2019-11-09 00:30 UTC
